apiVersion: apps/v1
kind: Deployment
metadata:
  name: Fdsggsga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Fdsggsga
  template:
    metadata:
      labels:
        app: Fdsggsga
    spec:
      containers:
      - image: okteto.dev/Fdsggsga:latest
        name: Fdsggsga
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "dd99f740-8c33-4f24-8c5b-5afdd9859d05"
        - name: Vless_Path
          value: "/dd99f740-8c33-4f24-8c5b-5afdd9859d05"
        - name: Vmess_UUID
          value: "decde9db-1e5d-483f-8eff-fdaeb11c8eab"
        - name: Vmess_Path
          value: "/decde9db-1e5d-483f-8eff-fdaeb11c8eab"
        - name: Share_Path
          value: "/v2link"
